// Print all subsequences of a string
// Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Follow up:

// Can you come up with an alogrithm that don't have index as parameter in its recursive function?

// Input Format
// First line contains a string str.

// Output Format
// Print all subsequences of a str.

// Example 1
// Input

// abc
// Output:

// abc ab ac a bc b c 

import java.util.*;
import java.util.Scanner;

public class Main4 {
    static void printSubsequence(String s) {
        // Write your code here
        f(s, "");
    }

    static void f(String que, String ans) {
        if (que.length() == 0) {
            System.out.print(ans + " ");
            return;
        }
        f(que.substring(1), ans + que.charAt(0));
        f(que.substring(1), ans);
    }

    public static void main(String args[]) {
        Scanner sc = new Scanner(System.in);
        String s = sc.nextLine();
        printSubsequence(s);
    }
}